name: bullet_train
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^4.0.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame: ^1.7.3
  flame_audio: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
  mockingjay: ^0.3.0

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flame_test: ^1.10.1
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
